In [621]:
import pandas as pd 
import numpy as np 


In [622]:
df=pd.read_csv("titanic/train.csv")

In [623]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [624]:
df.shape

(891, 12)

In [625]:
df=df.drop('Name', axis=1)
df=df.drop('Ticket', axis=1)
df=df.drop('Cabin', axis=1)

In [626]:
# set 0 for female and 1 for male
df['Sex']=df['Sex'].map({'female':1, 'male':0})


In [627]:
df.head(10)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    0  22.0      1      0   7.2500        S
1            2         1       1    1  38.0      1      0  71.2833        C
2            3         1       3    1  26.0      0      0   7.9250        S
3            4         1       1    1  35.0      1      0  53.1000        S
4            5         0       3    0  35.0      0      0   8.0500        S
5            6         0       3    0   NaN      0      0   8.4583        Q
6            7         0       1    0  54.0      0      0  51.8625        S
7            8         0       3    0   2.0      3      1  21.0750        S
8            9         1       3    1  27.0      0      2  11.1333        S
9           10         1       2    1  14.0      1      0  30.0708        C

In [628]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [629]:
df['Age'].isnull().sum()

np.int64(177)

In [630]:
#fill the null values in the age column to the median of age
df.fillna({'Age' : df['Age'].median()} , inplace=True)

In [631]:
df['Age'].isnull().sum()


np.int64(0)

In [632]:
# set the age of all children less than one year to 1 year
df.loc[df['Age'] < 1] = 1

In [633]:
df.Age.unique()

array([22. , 38. , 26. , 35. , 28. , 54. ,  2. , 27. , 14. ,  4. , 58. ,
       20. , 39. , 55. , 31. , 34. , 15. ,  8. , 19. , 40. , 66. , 42. ,
       21. , 18. ,  3. ,  7. , 49. , 29. , 65. , 28.5,  5. , 11. , 45. ,
       17. , 32. , 16. , 25. ,  1. , 30. , 33. , 23. , 24. , 46. , 59. ,
       71. , 37. , 47. , 14.5, 70.5, 32.5, 12. ,  9. , 36.5, 51. , 55.5,
       40.5, 44. , 61. , 56. , 50. , 36. , 45.5, 20.5, 62. , 41. , 52. ,
       63. , 23.5, 43. , 60. , 10. , 64. , 13. , 48. , 53. , 57. , 80. ,
       70. , 24.5,  6. , 30.5, 34.5, 74. ])

In [634]:
#now change the data type of age from float to int
df['Age']=df['Age'].astype(int)


In [635]:
df.Age.value_counts()


Age
28    204
24     31
30     27
22     27
18     26
     ... 
66      1
12      1
53      1
80      1
74      1
Name: count, Length: 70, dtype: int64

In [636]:
df.head()

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch     Fare Embarked
0            1         0       3    0   22      1      0   7.2500        S
1            2         1       1    1   38      1      0  71.2833        C
2            3         1       3    1   26      0      0   7.9250        S
3            4         1       1    1   35      1      0  53.1000        S
4            5         0       3    0   35      0      0   8.0500        S

In [637]:
df['Fare']=df['Fare'].astype(int)

In [638]:
df.head()

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare Embarked
0            1         0       3    0   22      1      0     7        S
1            2         1       1    1   38      1      0    71        C
2            3         1       3    1   26      0      0     7        S
3            4         1       1    1   35      1      0    53        S
4            5         0       3    0   35      0      0     8        S

In [639]:
df[df['PassengerId']==78]

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare Embarked
77           78         0       3    0   28      0      0     8        S

In [640]:
df.dropna(subset='Embarked', inplace=True)

In [641]:
df['Embarked'].dtype

dtype('O')

In [642]:
#drop the records in embarked where value is 1
df = df[df['Embarked'] != 1]


In [643]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [644]:
#now change the categorical values in embarked column to s:0 , C:1 and Q:2
df['Embarked']=df['Embarked'].map({'S':0, 'C':1 , 'Q':2})


In [645]:
df['Embarked'].unique()


array([0, 1, 2])

In [646]:
df.head()

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0            1         0       3    0   22      1      0     7         0
1            2         1       1    1   38      1      0    71         1
2            3         1       3    1   26      0      0     7         0
3            4         1       1    1   35      1      0    53         0
4            5         0       3    0   35      0      0     8         0

In [647]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [648]:
# normalize features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])


In [649]:
df.head()

PassengerId  Survived  Pclass  Sex       Age  SibSp  Parch      Fare  \
0            1         0       3    0 -0.589732      1      0 -0.495718   
1            2         1       1    1  0.663060      1      0  0.792067   
2            3         1       3    1 -0.276534      0      0 -0.495718   
3            4         1       1    1  0.428161      1      0  0.429878   
4            5         0       3    0  0.428161      0      0 -0.475596   

   Embarked  
0         0  
1         1  
2         0  
3         0  
4         0

In [650]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
X = df[features]
y = df['Survived']


In [651]:
# train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test= train_test_split(x,y , test_size=0.2, random_state=22)


In [652]:
'''
n_jobs specifies how many processors (cores) to use.
It is helpful when your dataset is large and you want to speed up the computation (especially during training or prediction).
⚙️ Common Values:
n_jobs=1: Use only one core (default).

n_jobs=4: Use 4 cores.

n_jobs=-1: Use all available cores.
'''
from sklearn.linear_model import LinearRegression
lr= LinearRegression(n_jobs=-1)
lr.fit(x_train , y_train)

LinearRegression(n_jobs=-1)

In [653]:
y_pred_lr=lr.predict(x_test)

In [654]:
from sklearn.metrics import mean_squared_error , r2_score
print("Linear Regression:")
print("MSE:", mean_squared_error(y_test, y_pred_lr))
print("R² Score:", r2_score(y_test, y_pred_lr))

Linear Regression:
MSE: 0.1444931567069906
R² Score: 0.39253541244319523


In [655]:
#using logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report , accuracy_score
model=LogisticRegression(max_iter=1000)
model.fit(x_train , y_train)

y_pred_log= model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Report:\n", classification_report(y_test, y_pred_log))


Accuracy: 0.8248587570621468
Report:
               precision    recall  f1-score   support

           0       0.81      0.93      0.87       108
           1       0.85      0.67      0.75        69

    accuracy                           0.82       177
   macro avg       0.83      0.80      0.81       177
weighted avg       0.83      0.82      0.82       177



In [656]:
y_pred_log

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0])

In [657]:
test_df=pd.read_csv('titanic/test.csv')
test_df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [658]:
test_df=test_df.drop('Name', axis=1)
test_df=test_df.drop('Ticket', axis=1)
test_df=test_df.drop('Cabin', axis=1)

In [659]:
# test_df.fillna({'Fare' : test_df['Fare'].median()} , inplace=True)

# test_df['Sex'].isna().sum()
print(test_df.isna().sum())  # Should return 0 for all


PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64


In [660]:
test_df.fillna({'Sex' : test_df['Sex'].mode()[0]} , inplace=True)

test_df['Sex']=test_df['Sex'].map({'female':1, 'male':0})
test_df.fillna({'Age' : test_df['Age'].median()} , inplace=True)
test_df.fillna({'Fare' : test_df['Fare'].median()} , inplace=True)
test_df.fillna({'Embarked' : test_df['Embarked'].mode()[0]} , inplace=True)
test_df['Embarked']=test_df['Embarked'].map({'S':0, 'C':1 , 'Q':2})
test_df.loc[test_df['Age'] < 1] = 1
test_df['Fare']=test_df['Fare'].astype(int)
test_df['Age']=test_df['Age'].astype(int)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
test_df[['Age', 'Fare']] = scaler.fit_transform(test_df[['Age', 'Fare']])


In [661]:
print(test_df.isna().sum())  # Should return 0 for all


PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64


In [662]:
binary_predictions=model.predict(test_df)

In [663]:
submission = pd.DataFrame({
    "PassengerId": test_df["PassengerId"],
    "Survived": binary_predictions
})

In [664]:
submission.to_csv('submission.csv' , index=False)