# Logistic regression implementation

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
from sklearn.datasets import make_classification


In [3]:
# create the dataset
# to generate a n class classification problem
x,y=make_classification(n_samples=1000 , n_features=10,
                   n_classes=2 , random_state=52)


In [4]:
x

array([[-1.48135488, -2.06314956,  0.16366798, ..., -1.62767013,
         0.46649376, -0.90487818],
       [-0.35554404,  0.31775672, -0.23773543, ..., -1.05291306,
         0.84969266,  0.5242196 ],
       [-1.40595358, -0.64981428,  0.25418381, ...,  2.73296083,
        -0.79519031, -0.72237423],
       ...,
       [ 2.25195442, -1.04681771, -0.03996119, ...,  2.56682103,
         0.15409745, -0.78043677],
       [-0.91531154,  0.01390034, -0.51961437, ..., -2.25512811,
         0.20179111,  0.31215577],
       [ 2.09488885, -0.75508831,  0.52874607, ..., -0.06712318,
         0.29631216,  1.15704404]], shape=(1000, 10))

In [5]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0   -1.481355 -2.063150  0.163668  1.254730  0.118024 -1.113321  1.195569   
1   -0.355544  0.317757 -0.237735 -1.225187  1.810316 -0.769992 -0.385018   
2   -1.405954 -0.649814  0.254184  0.260244 -2.213205  1.927212 -0.022052   
3    1.291240  0.688230  0.733283  1.276396 -1.427005  0.359518  0.901608   
4    0.920451  0.850359  0.011205  0.991326  0.421264 -1.195957  0.378580   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.692369  0.384873 -1.571855  1.778066 -1.096293 -0.359056  0.743843   
996  0.574657  1.278228  0.507436 -0.187430  0.290304 -0.130680 -0.341123   
997  2.251954 -1.046818 -0.039961 -0.374639 -1.551655  1.794918 -0.998392   
998 -0.915312  0.013900 -0.519614 -0.134237  1.757713 -1.588289  1.292241   
999  2.094889 -0.755088  0.528746  1.444694 -1.180949 -0.011853 -1.182151   

            7         8         9  
0   -1.627670  0.466494 -0.904878  
1   -1.052913  0.849693  0.524220  
2    2.732961 -0.795190 -0.722374  
3    0.467114 -0.600599 -0.831882  
4   -1.736081  0.177616  0.761239  
..        ...       ...       ...  
995 -0.572718 -0.655702 -0.312720  
996 -0.179409 -1.394802 -0.351650  
997  2.566821  0.154097 -0.780437  
998 -2.255128  0.201791  0.312156  
999 -0.067123  0.296312  1.157044  

[1000 rows x 10 columns]

In [6]:
y

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test= train_test_split(x,y,test_size=0.3 , random_state=33)


In [9]:
# model training
from sklearn.linear_model import LogisticRegression

In [10]:
logistic=LogisticRegression()

In [11]:
logistic.fit(x_train, y_train)

LogisticRegression()

In [12]:
y_pred=logistic.predict(x_test)

In [13]:
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0])

In [14]:
# to check what is the probability of a new test data to be in one of the two classes
# logistic.predict_proba(x_test)

In [15]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report


In [16]:
score=accuracy_score(y_test, y_pred)
print(score)
cm=confusion_matrix(y_test, y_pred)
print(cm)
report=classification_report(y_test, y_pred)
print(report)

0.8766666666666667
[[130  17]
 [ 20 133]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       147
           1       0.89      0.87      0.88       153

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



# Hyperparameter tuning and cross validation


Hyperparameter tuning is the process of choosing the best set of hyperparameters for a machine learning model to improve its performance.

1. C  : Inverse of regularization strength. Smaller C means stronger regularization (simpler model).
2. penalty :	Type of regularization. Common options: 'l1', 'l2', 'elasticnet', or None.
3. solver  :	Algorithm used for optimization. Options: 'liblinear', 'saga', 'lbfgs', etc. Some solvers support only certain penalties.
4. max_iter  :	Maximum number of iterations taken for convergence. Increase if the model doesn’t converge.

In [17]:
model=LogisticRegression()
penalty=['l1' , 'l2','elasticnet']
c_value=[100,10,1.0,0.1 , 0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag' , 'saga']
mIter=[100,200]

In [18]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

Regularization (C, penalty) controls overfitting.

Solver affects convergence and speed.

Right combination gives better accuracy, lower loss, and generalizes well to unseen data.

In [19]:
params=dict(penalty=penalty,C=c_value , solver=solver, max_iter=mIter)

In [20]:
# Grid search CV
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model , param_grid=params , scoring='accuracy', cv=cv, n_jobs=-1)


In [21]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [100, 200],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [22]:
grid.fit(x_train, y_train)

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
400 fits failed out of a total of 750.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [100, 200],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [23]:
grid.best_params_

{'C': 0.01, 'max_iter': 100, 'penalty': 'l1', 'solver': 'saga'}

In [24]:
grid.best_score_

np.float64(0.8757142857142858)

In [25]:
y_pred=grid.predict(x_test)

In [26]:
score=accuracy_score(y_test, y_pred)
print(score)
cm=confusion_matrix(y_test, y_pred)
print(cm)
report=classification_report(y_test, y_pred)
print(report)

0.8666666666666667
[[127  20]
 [ 20 133]]
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       147
           1       0.87      0.87      0.87       153

    accuracy                           0.87       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.87      0.87      0.87       300



Grid Search

Try all combinations of hyperparameters from a predefined grid.

Very accurate but computationally expensive.

Example: Try every combination of max_depth = [3, 5, 7] and min_samples_split = [2, 4].

# Randomized search CV

In [27]:

model=LogisticRegression()

from sklearn.model_selection import RandomizedSearchCV
rcv=RandomizedSearchCV(estimator=model ,param_distributions=params, n_jobs=-1 )

In [28]:
rcv.fit(x_train, y_train)

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
10 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\sawan\AppData\Roaming\Python\Python313\site-pa

RandomizedSearchCV(estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'max_iter': [100, 200],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']})

In [29]:
rcv.best_score_

np.float64(0.8714285714285716)

In [30]:
rcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'max_iter': 100, 'C': 10}

In [31]:
y_pred=rcv.predict(x_test)

In [32]:
score=accuracy_score(y_test, y_pred)
print(score)
cm=confusion_matrix(y_test, y_pred)
print(cm)
report=classification_report(y_test, y_pred)
print(report)

0.8766666666666667
[[130  17]
 [ 20 133]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       147
           1       0.89      0.87      0.88       153

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



In [33]:
# when we have large number of parameters randomized cv takes less time than grid search

 # logistic regression for multi class classification

In [58]:
# create the database
x, y= make_classification(n_samples=1000 , n_features=10 , n_informative=3,n_classes=3, random_state=22)

In [59]:
y

array([1, 2, 1, 1, 2, 1, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 2, 2,
       1, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 2, 0, 2,
       1, 1, 2, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1, 2, 1, 2,
       1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 1, 1, 0, 0, 1,
       0, 2, 2, 1, 1, 2, 2, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 1, 1, 2, 2, 0,
       1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1, 0, 2, 2, 0, 0, 2, 1, 1,
       0, 1, 1, 2, 2, 1, 1, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 1, 0, 2, 2, 2,
       2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 2, 1, 0,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 0, 0, 2, 1, 2, 1, 1, 2, 2, 2,
       2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 0, 0, 1, 0, 1, 2, 1, 1, 2,
       1, 0, 2, 2, 2, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 2, 0, 0, 0, 2, 1, 1,
       1, 1, 1, 0, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1,

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test= train_test_split(x,y,test_size=0.3 , random_state=33)

In [66]:
# logreg=LogisticRegression(multi_class='ovr')
# the above method is depricated
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

logreg = OneVsRestClassifier(LogisticRegression())
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_test)



In [67]:
y_pred

array([1, 2, 0, 2, 0, 1, 0, 0, 2, 2, 1, 2, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 2, 0, 0, 2, 2, 0, 2, 0, 1, 2, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0,
       2, 2, 0, 0, 0, 0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       1, 1, 1, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 1, 1, 1, 0, 1, 2, 1, 0, 2, 2, 1, 0, 0, 2, 2, 1, 2, 0, 0,
       2, 0, 0, 2, 1, 1, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 2, 1, 0, 0, 2, 2,
       0, 2, 2, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 1, 2, 2, 1, 2, 0, 1, 2, 2, 0, 0, 2, 0, 2, 2, 1, 2, 2, 0,
       1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 0, 0, 2, 2, 2, 0, 1, 0, 2, 0, 0, 1,
       0, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1, 2, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 1,
       2, 2, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 0,
       2, 1, 0, 2, 2, 1, 1, 1, 1, 1, 0, 0, 2, 2])

In [68]:
score=accuracy_score(y_test, y_pred)
print(score)
cm=confusion_matrix(y_test, y_pred)
print(cm)
report=classification_report(y_test, y_pred)
print(report)

0.7233333333333334
[[76  9  5]
 [28 47 24]
 [ 0 17 94]]
              precision    recall  f1-score   support

           0       0.73      0.84      0.78        90
           1       0.64      0.47      0.55        99
           2       0.76      0.85      0.80       111

    accuracy                           0.72       300
   macro avg       0.71      0.72      0.71       300
weighted avg       0.71      0.72      0.71       300



In [70]:
# hyperparamter tuning
logreg = OneVsRestClassifier(LogisticRegression(solver='saga', max_iter=10000))

from scipy.stats import loguniform
-> This imports a logarithmic uniform distribution from scipy, which is used to sample values for the hyperparameter C during hyperparameter tuning.

🔍 What is loguniform(1e-4, 1e2)?
This creates a distribution of values that are:

logarithmically spaced between 1e-4 (0.0001) and 1e2 (100)

So instead of sampling linearly (like 1, 2, 3...), it samples values like:
0.0001, 0.001, 0.01, 0.1, 1, 10, 100


📘 Why loguniform for C?
C is the inverse of regularization strength in Logistic Regression:

High C → low regularization (model fits more to the training data)

Low C → high regularization (model is penalized more for complexity)

👉 The range of good C values varies exponentially, so we use a log scale to explore the space efficiently.

In [72]:
from scipy.stats import loguniform

params = {
    'estimator__C': loguniform(1e-4, 1e2),  
    'estimator__penalty': ['l2', 'l1'],                 
}


In [73]:
random_search = RandomizedSearchCV(
    estimator=logreg,
    param_distributions=params,
    n_iter=20,
    scoring='accuracy',
    cv=5,
    random_state=42,
    n_jobs=-1
)


In [75]:
random_search.fit(x_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000,
                                                                              solver='saga')),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'estimator__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001D4EBBC12B0>,
                                        'estimator__penalty': ['l2', 'l1']},
                   random_state=42, scoring='accuracy')

In [77]:
random_search.best_params_

{'estimator__C': np.float64(0.06317967091932514), 'estimator__penalty': 'l2'}

In [78]:
random_search.best_score_

np.float64(0.6799999999999999)

In [79]:
# Predict with best estimator
best_model = random_search.best_estimator_
y_pred = best_model.predict(x_test)

In [80]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.73      0.83      0.78        90
           1       0.62      0.48      0.55        99
           2       0.78      0.84      0.81       111

    accuracy                           0.72       300
   macro avg       0.71      0.72      0.71       300
weighted avg       0.71      0.72      0.71       300

