In [2]:
import numpy as np

In [3]:
kanto=np.array([73,67,43])
kanto

array([73, 67, 43])

In [4]:
weights=np.array([0.3 ,0.2,0.5])

In [5]:
type(kanto)

numpy.ndarray

In [6]:
kanto[1]


np.int64(67)

In [7]:
print(weights[2])

0.5


Operating on numpy array

we can compute the dot product of two vectors using np.dot function

In [8]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [9]:
print(np.dot(kanto,weights))

56.8


In [10]:
kanto*weights

array([21.9, 13.4, 21.5])

In [11]:
#another method to calculate the dot product
print((kanto*weights).sum())

56.8


python loops vs numpy arrays

In [12]:
a1=list(range(1000000))
a2=list(range(1000000,2000000))

#numpy arrays
a1_np=np.array(a1)
a2_np=np.array(a2)

In [13]:
%%time
result=0
for x,y in zip(a1,a2):
    result+=x*y
(result)

CPU times: total: 156 ms
Wall time: 158 ms


833332333333500000

In [14]:
%%time
(np.dot(a1_np,a2_np))
#numpy arrays are 100times faster than loops

CPU times: total: 15.6 ms
Wall time: 1.6 ms


np.int64(833332333333500000)

In [15]:
climate_data=np.array([
    [73,67,43],
    [91,88,64],
    [87,134, 58],
    [102,43,37],
    [69,96,70]
])
print(climate_data)

[[ 73  67  43]
 [ 91  88  64]
 [ 87 134  58]
 [102  43  37]
 [ 69  96  70]]


In [16]:
climate_data.shape

(5, 3)

In [17]:
weights.shape

(3,)

In [18]:
climate_data.dtype

dtype('int64')

In [19]:
arr3d=np.array([
    [
        [1 , 3, 4],
        [6 ,4 ,66]
    ],
    [
        [44,3 ,32],
        [23, 45 ,33]
    ]
])
arr3d


array([[[ 1,  3,  4],
        [ 6,  4, 66]],

       [[44,  3, 32],
        [23, 45, 33]]])

In [20]:
arr3d.shape

(2, 2, 3)